### PR TITLE
Split into 3 modules

### PR DESCRIPTION
**Pull request by bmcdonald3**
Not sure if this is the best way to split the modules up, but I found myself wanting to refactor the code to understand it better anyway.

### CODE REVIEW

**Comment by mhmerrill** [comment]
@bmcdonald3 i would have refactored a different way

data structures like `GenList`, `GenValue`, `Env` in their own module
Lisp `parse`, `tokenize`, and `eval` in another module
test structure and main in it's own module

**Comment by bmcdonald3** [comment]
@mhmerrill do you have a preference on how you would name those modules?

**Comment by mhmerrill** [comment]
> @mhmerrill do you have a preference on how you would name those modules?

just a wag:
maybe LispSupport.chpl, LispInterp.chpl, TestLisp.chpl

**Comment by bmcdonald3** [comment]
Closing as https://github.com/mhmerrill/LisExpr/pull/16 was merged to handle this refactor

**Pull request closed without merging**
